stages:
  - deployment

Deploy to stage:
  stage: deployment
  image:
    name: minkbear/php-deployer:7
    entrypoint: [ "" ]
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh-deactivate-key-checking
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - apk add --no-cache icu-dev
    - docker-php-ext-install intl
  script:
    - echo "Deploy to Staging..."
    # Fix permissions
    - find /builds/`echo $CI_PROJECT_PATH` -type d -print0 | xargs -0 chmod 0755
    - find /builds/`echo $CI_PROJECT_PATH` -type f -print0 | xargs -0 chmod 0664
    - composer install --no-dev --no-ansi --no-interaction --no-scripts --prefer-dist --ignore-platform-reqs
    - dep deploy staging -vvv
  resource_group: staging
  environment:
    name: staging
    url: https://wacken-foundation.tnt-digitalagentur.de
  only:
    - develop

Deploy to Master:
  image: chialab/php:7.4
  cache:
    paths:
      - .apt/
  before_script:
    - export APT_DIR=$CI_PROJECT_DIR/.apt && export APT_STATE_LISTS=$APT_DIR/lists && export APT_CACHE_ARCHIVES=$APT_DIR/archives
    - printf "dir::state::lists    ${APT_STATE_LISTS};\ndir::cache::archives    ${APT_CACHE_ARCHIVES};\n" > /etc/apt/apt.conf
    - mkdir -p "${APT_STATE_LISTS}/partial" && mkdir -p "${APT_CACHE_ARCHIVES}/partial"
    - apt-get update -qy
    - apt-get install rsync -y
    - 'command -v ssh-agent >/dev/null || ( apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  stage: deployment
  script:
    - echo "hello deploy production cached - START"
    - vendor/bin/dep deploy production -vv
  environment:
    name: production
    url: https://staging.wacken-foundation.tnt-digitalagentur.de/
  when: manual
  only:
    - master
